alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias jn='jupyter notebook'
alias sa='source activate'
alias ML='cd /home/pilou/StaffMe/Algo/ML/matching-ML'
alias matching='cd /home/pilou/StaffMe/Algo/matching_api'
alias DtScience='cd /home/pilou/StaffMe/Projets_ML/datascience'
alias Python='cd /home/pilou/StaffMe/Python'
alias deact='source deactivate'
alias matching-dock='cd /home/pilou/dockers/docker-tests/dockers'
alias ebash='nano ~/.bashrc'
alias epromt='nano ~/.bash_prompt'
alias dostop='docker stop $(docker ps -aq) && docker rm $(docker ps -aq)'
alias glog='git log --graph --abbrev-commit --decorate --format=format:'\''%C(bold blue)%h%C(reset) - %C(bold cyan)%ad%C(reset) %C(bold green)(%ar)%C(reset)%C(auto)%d%C(reset)%n'\'''\''%C(white)%s%C(reset) %C(dim white)- %an%C(reset)'\'' --all --date=short'
alias mandel='~/mandel.sh'
alias czbraa='cd /home/pilou/ChNeuf/zbraa'
